Docs: 要致富，先撸树
KomoriDev/NoneBotX pull request #13
Opened 2023-08-23 14:01 UTC by KomoriDev

2023-08-23 14:34 UTC, NCBM reviewed
看来又要多出好几个 PR 了（

2023-08-23 14:34 UTC, NCBM commented on CONTRIBUTING.md
>  在将代码推送到主分支时，将触发构建，然后将生成的文件发送到 Netlify 以发布到生产环境。
（虽然不是这个 PR 该干的）

2023-08-23 14:37 UTC, KomoriDev commented
> 看来又要多出好几个 PR 了（

快拉点人来做苦力，孩纸要开学了 （bushi

2023-08-23 20:30 UTC, NCBM reviewed
把 pdm 的描述修正一下，再加上 Console 和实际平台适配器的优势比较就差不多了

2023-08-23 20:30 UTC, NCBM commented on docs/guide/create_env.md
> +1. 安装 `PDM` 虚拟环境
pdm 不是虚拟环境，是集成项目管理器

2023-08-23 20:30 UTC, NCBM commented on docs/guide/create_env.md
> +   [?] 要使用哪些适配器? Console (基于终端的交互式适配器)
使用 Console 适配器的好处需要写一段

2023-08-23 20:33 UTC, NCBM requested changes
不太对劲，正常的流程是先用 nb-cli 建项目，然后再介入 pdm。

2023-08-24 05:38 UTC, NCBM reviewed
我再走一下实际流程看看

2023-08-24 09:24 UTC, NCBM approved these changes

2023-08-24 09:54 UTC, KomoriDev commented on docs/public/avatar/ero.jpg
这里的图片名字也改一下吧，然后就是 👇
https://github.com/KomoriDev/NoneBotX/blob/282aa0cce7df2324dc2afa4a1a7bab52e069b19e/docs/guide/create_env.md?plain=1#L307
~~这头像会不会有点非主流~~

2023-08-24 10:34 UTC, merged