Docs: GO-CQHTTP 的安装与配置
KomoriDev/NoneBotX pull request #23
Opened 2023-08-25 01:29 UTC by KomoriDev

2023-08-25 06:20 UTC, NCBM requested changes
内容安排有点问题，指路指的 dev 版 gocq，配置文件用的 1.1.0 的，顺序也不是特别好

2023-08-25 08:07 UTC, KomoriDev commented
> 内容安排有点问题，指路指的 dev 版 gocq，配置文件用的 1.1.0 的，顺序也不是特别好

大部分抄的[这里](https://docs.go-cqhttp.org/guide/quick_start.html)其实 [手动狗头]

2023-08-26 09:43 UTC, NCBM commented
> > 内容安排有点问题，指路指的 dev 版 gocq，配置文件用的 1.1.0 的，顺序也不是特别好
> 
> 大部分抄的[这里](https://docs.go-cqhttp.org/guide/quick_start.html)其实 [手动狗头]

今天看了下才发现这玩意又新又旧（

2023-08-26 09:47 UTC, NCBM approved these changes

2023-08-26 09:48 UTC, NCBM commented
再看看还有什么地方需要改

2023-08-26 11:58 UTC, merged