新增 NoneBot GUI 一键部署教程
KomoriDev/NoneBotX pull request #58
Opened 2024-07-25 08:56 UTC by XTxiaoting14332

2024-07-25 13:43 UTC, KomoriDev requested changes

2024-07-25 13:43 UTC, KomoriDev commented on docs/.vitepress/sidebar.ts
> +      { text: '通过 NoneBot Flutter GUI 一键部署', link: '/before/gui_deploy' },
```suggestion
      { text: '通过 NoneBot GUI 一键部署', link: '/before/gui_deploy' },
```

2024-07-25 13:43 UTC, KomoriDev commented on docs/before/gui_deploy.md
> +NoneBot Flutter GUI 并不提供 `nb-cli` 的安装，请在使用前先安装 `nb-cli`
提一嘴安装的步骤

2024-07-25 13:43 UTC, KomoriDev commented on docs/before/gui_deploy.md
> +前往 [Github Releases](https://github.com/NonebotGUI/nonebot-flutter-gui/releases) 下载 `v0.2.0` 或者更新版的 NoneBot Flutter GUI
```suggestion
前往 [Github Release](https://github.com/NonebotGUI/nonebot-flutter-gui/releases) 下载最新版的 NoneBot GUI
```

2024-07-25 13:43 UTC, KomoriDev commented on docs/before/gui_deploy.md
> +启动软件，在侧边栏中找到 `快速部署` 并选择 `Lagrange.Onebot`
```suggestion
启动软件，在侧边栏中找到 `快速部署` 并选择 `Lagrange.OneBot`
```

NoneBot GUI 也应该改改（

2024-07-25 13:43 UTC, KomoriDev commented on docs/before/gui_deploy.md
> +填好相关配置并选择存放 Bot 的目录，如果您的网络环境无法访问 github 可以使用镜像站下载，完成后点击下方按钮进入下一步
```suggestion
填好相关配置并选择存放 Bot 的目录，如果您的网络环境无法访问 Github 可以使用镜像站下载，完成后点击下方按钮进入下一步
```

2024-07-25 13:43 UTC, KomoriDev commented on docs/before/gui_deploy.md
> +在下拉框中选择时候当前系统的 release 并下载
```suggestion
在下拉框中选择当前系统的版本并下载
```

2024-07-25 13:43 UTC, KomoriDev commented on docs/before/gui_deploy.md
> +下载完成后点击 `部署` 按钮，并等待部署完成，其中请确保网络正常连接
```suggestion
下载完成后点击 `部署` 按钮，并等待部署完成，期间请确保网络正常连接
```

2024-07-25 13:44 UTC, KomoriDev commented
图片最好使用 `.webp` 格式，这有个[在线转换平台](https://converter.11zon.com/zh-cn/png-to-webp)

2024-07-26 05:45 UTC, KomoriDev commented
为什么全是一级标题

2024-07-27 03:34 UTC, XTxiaoting14332 commented
怎么修

2024-10-19 16:12 UTC, XTxiaoting14332 commented
已修正

2024-10-19 19:09 UTC, KomoriDev requested changes
动 package.json 干嘛

2024-10-19 19:14 UTC, XTxiaoting14332 commented
> 动 package.json 干嘛

我没动这玩意

2024-10-19 19:19 UTC, KomoriDev commented
> > 动 package.json 干嘛
> 
> 我没动这玩意

![image](https://github.com/user-attachments/assets/a2ca5e49-366d-4d32-8501-a8806bcfd247)

2024-10-20 03:05 UTC, closed without merging